### ISSUE TITLE
Fatal error when 

### ISSUE THREAD

**Issue by halftrainedharry** [BobRay/newspublisher#61]
When the rich text editor is used for _NewsPublisher_ (in the frontend)

```
[[!NewsPublisher?
    &initrte=`1`
    &rtcontent=`1`
    ...
]]
```

and a rich text editor extra (like for example "TinyMCE Rich Text Editor") is installed in the backend, a fatal error occurs:

```
Fatal error: Uncaught Error: Call to a member function addJavascript() on null in ...\core\components\tinymcerte\src\Plugins\Events\OnRichTextEditorInit.php:53 Stack trace: 
#0 ...\core\components\tinymcerte\src\Plugins\Events\OnRichTextEditorInit.php(41): TinyMCERTE\Plugins\Events\OnRichTextEditorInit->initTinyMCE() 
#1 ...\core\components\tinymcerte\src\Plugins\Plugin.php(50): TinyMCERTE\Plugins\Events\OnRichTextEditorInit->process() 
#2 ...\core\cache\includes\elements\modx\revolution\modplugin\22.include.cache.php(24): TinyMCERTE\Plugins\Plugin->run() 
#3 ...\core\src\Revolution\modScript.php(88): include('C:\\wamp64\\www\\m...') 
#4 ...\core\src\Revolution\modX.php(1710): MODX\Revolution\modScript->process(NULL) 
#5 ...\core\components\newspublisher\model\newspublisher\newspublisher.class.php(843): MODX\Revolution\modX->invokeEvent('OnRichTextEdito...', Array) 
#6 ...\core\c in ...\core\components\tinymcerte\src\Plugins\Events\OnRichTextEditorInit.php on line 53
```

The problem seems to be this line in the code:

https://github.com/BobRay/newspublisher/blob/159898caa0ce17f63b214bf2d0198bec33f7a7af/core/components/newspublisher/model/newspublisher/newspublisher.class.php#L843

---

MODX 3.0.3-pl
NewsPublisher 3.1.5-pl

Related thread in the MODX forum:
https://community.modx.com/t/newspublisher-rich-text-editor-cant-get-it-to-work/6929

**Comment by BobRay** [comment]
GitHub hasn't always been good about notifying me of issues. I don't think I've seen this before. I confess that I don't have any good ideas on how to solve it. 

It seems to me that If NP doesn't load an RTE here because one is already loaded, it could be trying to use an incompatible RTE version from that point on. A typical user of NP wouldn't be simultaneously logged in to the Manager (since the main point of NP is to allow users to edit things without letting them in to the Manager), so it would seldom affect front-end users. From the description,  I'm assuming that this issue doesn't affect the Manager.

**Comment by BobRay** [comment]
Closing --  I think this is solved. reopen if it's still an issue.
